#!/bin/sh

#
# X configuration
#

# merge xresources
xresources=$XDG_CONFIG_HOME/X11/xresources
if [ -f "$xresources" ]; then
    xrdb -merge "$xresources"
fi

# set default cursor
xsetroot -cursor_name left_ptr &

# set startup backlight level
xbacklight -set 20 &

# set PulseAudio default volume
pactl set-sink-volume @DEFAULT_SINK@ 70% &
pactl set-source-mute @DEFAULT_SOURCE@ 1 &

# set default keyboard layout
setxkbmap es &

# set touchpad properties
xinput set-prop "SYNA2393:00 06CB:7A13 Touchpad" "libinput Tapping Enabled" 1 &
xinput set-prop "SYNA2393:00 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1 &
xinput set-prop "SYNA2393:00 06CB:7A13 Touchpad" "libinput Disable While Typing Enabled" 0 &


#
# Autostart
#

# Set Wallpaper
#feh --no-fehbg --bg-fill "$(shuf -zen1 .config/wallpapers/* | tr '\0' '\n')" &
feh --no-fehbg --bg-fill .config/wallpapers/wall-2.jpg &

# Programs
sxhkd &
polybar xpsbar &
picom -b &
nextcloud &
redshift &
dunst &
flameshot &
protonmail-bridge --noninteractive &
#xsettingsd &
#/usr/bin/libinput-gestures &
#/usr/lib/notification-daemon-1.0/notification-daemon &

# Start gnome-keyring-daemon
eval "$(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)"
export "$(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)"
dbus-update-activation-environment --systemd DISPLAY


#
# Start WM
#

# execute window manager
exec bspwm
