#!/bin/sh

# merge xresources
xresources=$XDG_CONFIG_HOME/X11/xresources
if [ -f "$xresources" ]; then
    xrdb -merge "$xresources"
fi

# source xinitrc.d files
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
    done
    unset f
fi

# set default cursor
xsetroot -cursor_name left_ptr &

# set startup backlight level
xbacklight -set 20 &

# set keyboard layout
setxkbmap es &

# set touchpad properties
xinput set-prop "SYNA2393:00 06CB:7A13 Touchpad" "libinput Tapping Enabled" 1 &
xinput set-prop "SYNA2393:00 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1 &
xinput set-prop "SYNA2393:00 06CB:7A13 Touchpad" "libinput Disable While Typing Enabled" 0 &

# set volume
pactl set-sink-volume @DEFAULT_SINK@ 70% &
# mute microphone
pactl set-source-mute @DEFAULT_SOURCE@ 1 &

# autostart
sxhkd &
dunst &
picom -b &
redshift &
nextcloud &
flameshot &
protonmail-bridge --noninteractive &
greenclip daemon &
# gnome-keyring-daemon
eval "$(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)"
export "$(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)"
dbus-update-activation-environment --systemd DISPLAY

# execute window manager
exec bspwm

