#! /bin/sh

#
# Colors
#

focused=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
normal=$(xrdb -query | grep 'color8:'| awk '{print $NF}')

#
# Monitors
#

bspc monitor -d 1 2 3 4 5

#
# Configs
#

# Color of the border of an unfocused window
bspc config normal_border_color         "$normal"
# Color of the border of a focused window of an unfocused monitor
bspc config active_border_color         "#000000"
# Color of the border of a focused window of an focused monitor
bspc config focused_border_color        "$focused"
# Color of the node --presel-{dir,ratio} message feedback area
bspc config presel_feedback_color       "#000000"
# Default split ratio
bspc config split_ratio                 0.50
# Remove borders of tiled windows for the monocle desktop layout
bspc config borderless_monocle          true
# Remove gaps of tiled windows for the monocle desktop layout
bspc config gapless_monocle             true
# Set the desktop layout to monocle if there's only one tiled window in the tree
bspc config single_monocle              false
# Focus the window under the pointer
bspc config focus_follows_pointer       true
# When focusig a window, put the pointer at its center
bspc config pointer_follows_focus       false
# Padding space added at the sides of the monitor or desktop
bspc config top_padding                 0
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0
# Size of the gap that separates windows
bspc config window_gap                  8
# Window border width
bspc config border_width                1

#
# Rules
#

# Remove all rules
bspc rule -r *:*
# Pdf viewer
bspc rule -a Zathura state=tiled follow=on

