#! /bin/sh

#
# Colors
#

normal=$(xrdb -query | grep 'background:'| awk '{print $NF}')
active=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
focused=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
presel=$(xrdb -query | grep 'color8:'| awk '{print $NF}')


# Color of the border of an unfocused window
bspc config normal_border_color         "$normal"
# Color of the border of a focused window of an unfocused monitor
bspc config active_border_color         "$active"
# Color of the border of a focused window of an focused monitor
bspc config focused_border_color        "$focused"
# Color of the node --presel-{dir,ratio} message feedback area
bspc config presel_feedback_color       "$presel"
# Default split ratio
bspc config split_ratio                 0.50
# Remove borders of tiled windows for the monocle desktop layout
bspc config borderless_monocle          true
# Remove gaps of tiled windows for the monocle desktop layout
bspc config gapless_monocle             false
# Set the desktop layout to monocle if there's only one tiled window in the tree
bspc config single_monocle              false
# Focus the window under the pointer
bspc config focus_follows_pointer       true
# When focusig a window, put the pointer at its center
bspc config pointer_follows_focus       false
# Padding space added at the sides of the monitor or desktop
bspc config top_padding                 0
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0
# Size of the gap that separates windows
bspc config window_gap                  8
# Window border width
bspc config border_width                1

#
# Rules
#

# Remove all rules
bspc rule -r '*:*'
# Pdf viewer
bspc rule -a Zathura state=tiled follow=on


###############
# monitor setup
###############
# bspwm monitors -> https://www.reddit.com/r/bspwm/comments/j0ywxi/windows_are_not_staying_in_the_workspace_when/
# udev rule -> https://bbs.archlinux.org/viewtopic.php?pid=1329375#p1329375
# KERNEL=="card0", SUBSYSTEM=="drm", ENV{DISPLAY}=":0", ENV{XAUTHORITY}="/home/pport/.config/X11/xauthority", RUN+="source /home/pport/.config/bspwm/bspwmrc"


# kill all polybar instances
killall -q polybar
while pgrep -x polybar >/dev/null; do sleep 1; done
monitor_count=$(xrandr --query | grep ' connected' | wc -l)
if [[ $monitor_count -eq 3 ]]; then
    xrandr \
        --output eDP1 --mode 1920x1080 --rate 60 --pos 0x1080 \
        --output DP1 --mode 1920x1080 --rate 60 --pos 0x0 \
        --output DP3 --mode 1920x1080 --rate 60 --pos 1920x155
    polybar main-DP1 &
    polybar secondary-eDP1 &
    polybar secondary-DP3 &
    bspc monitor eDP1 -d 0
    bspc monitor DP1 -d 1 2 3 4 5
    bspc monitor DP3 -d 6
elif [[ $monitor_count -eq 2 ]]; then
    secondary_monitor=$(xrandr --query | grep ' connected' | tail -n1 | cut -d ' ' -f1)
    xrandr \
        --output eDP1 --mode 1920x1080 --rate 60 \
        --output $secondary_monitor --mode 1920x1080 --rate 60 --above eDP1
    polybar main-$secondary_monitor &
    polybar secondary-eDP1 &
    bspc monitor eDP1 -d 0
    bspc monitor $secondary_monitor -d 1 2 3 4 5 6
else
    xrandr --output eDP1 --mode 1920x1080 --rate 60
    polybar main-eDP1 &
    bspc monitor eDP1 -d 1 2 3 4 5 6
fi
feh --no-fehbg --bg-scale ~/.local/share/wallpapers/planets/not-nasa-pluto.jpg
    #feh --no-fehbg --bg-fill "$(find $HOME/.local/share/wallpapers/ -iname '*.jpg' -print0 | shuf -z -n1 | tr '\0' '\n')"
